---
title: "Let's upgrade posters"
date: 2013-05-23
categories: ["President's Column"]
---

Written by Robin Hogarth

This past week, I have spent some time “judging” abstracts for a conference and it got me to think a bit about the purpose of these conferences, their value, and whether they could be better organized.

It is clear that most scientists enjoy going to conferences. In addition to direct work relevance, it is fun to visit different countries and cities, to connect with old friends and to meet others for the first time. The first conferences I attended were at the beginning of the 1970s and I still meet people from those days at different events.  We rarely connect between events but when we do it’s always fun.  I once heard Sarah Lichtenstein mention these kinds of relationships – she used the expression “conference friends.” I also remember the excitement I experienced at those first conferences of actually meeting the people whose papers I had been reading.
<div align="justify">In the intervening years, my sense is that conferences on judgment and decision making have increased in frequency, type, and scope. In the early days, those attending the SPUDM and SJDM conferences could fit into a single meeting room and all sessions were plenary. I don’t know if all submissions for presentations were accepted, but my guess is that it was a high percentage. Nowadays, we have parallel sessions, poster sessions, and many papers don’t get accepted for presentation. Fortunately, however, these large conferences are not the only events that take place and recent years have seen an increase in the number of smaller conferences – or meetings – dealing with specific topics.  I personally find these latter events most useful. It is wonderful to think that in the same room you can have assembled almost all the people in the world who are working on the same topic as yourself!   It is an incredible opportunity to exchange concrete ideas.</div>
Given the high value of the smaller meetings, the natural question to ask is whether these will not eventually replace the larger meetings. In other words, if one can attend a few smaller meetings, why bother attending the larger meetings? And this is particularly the case if one has to compete (by submitting an extended abstract) to the organizers of the larger conferences.

What will happen?  Before making any predictions, it may be interesting to examine what has happened in other scientific disciplines. My impressions (not based on hard data) are the following.  First, like all good JDM types, let’s think base rates. I suspect that if you look at all scientific societies, most have grown internationally in recent years. There is just a lot of activity and this has been facilitated by the ease with which we can now travel and communicate across borders. Second, as knowledge advances and essentially becomes more specialized, this is matched by the organizational structures of scientific societies. Thus, one either gets new societies being launched or the older societies create new divisions. This is clearly visible when one thinks about the development of journals in the fields related to judgment and decision making. I suspect that the key variable in all this is the number of active scientists in any field. That is, for a field to be viable on its own (i.e., hold regular meetings, publish journals, and so on) there needs to be a certain minimum number of researchers. I don’t know what this minimum is nor where EADM lies precisely on the distribution of societies but it would be intriguing to attempt a sociological study of this type. Moreover, given the obsession that people seem to have with impact factors and numbers of citations, I would not be surprised to learn that people have started to address these issues using these kinds of data in relation to membership of professional societies. In short, it would be interesting to have some more concrete evidence about the way in which scientific societies have been established, grown (or not grown), broken up, continued or just faded away. What factors distinguish the societies that are more and less “successful”?  I suspect that there are some fascinating regularities in all of this as well as illuminating exceptions.

But let me be more prosaic and get back to the current reality of decision making research where many papers are rejected for the major meetings. Is there anything that can be done about this?  The present system is that most conferences entrust the reading of abstracts to a committee of referees. Moreover – as I have been led to believe– inter-rater reliability of the referees is far from perfect (and having been a referee I understand. It is a very difficult task!)  But what, we can ask, is the alternative?  One might be to select papers at random (e.g., if only 40% of papers can be selected, every applicant has an explicit 40% chance and there are rules to avoid people submitting multiple papers.) Variations on this theme could involve letting people’s odds depend on different characteristics such as whether they presented at the previous conference. However, one can easily see how that could easily induce many dysfunctional consequences. As an experiment, I am intrigued by the notion of applying the random rule and then seeing whether this actually changes the experience of the conference as experienced by the participants (just kidding! This could lead to all kinds of problems!) In short, I think we are “stuck” with using referees in the same way that we need referees for journals and grant reviews. They are not perfect but it is really hard to come up with a better alternative.

In conferences, however, there is an alternative to the presented paper or symposium. This is the poster and my suggestion is that we need to take actions that make this option more attractive to potential attendees. I will be honest and say that, in general, I prefer making a live presentation to an audience as opposed to presenting a poster. At the same time, however, each time I have presented a poster I have received more insightful comments than the usual reactions to a 20-minute presentation.  What I think is needed are ways to make posters more attractive to presenters so that they are not just a “consolation” for those who fail to have their papers accepted (or a way to ensure funding to attend the conference).
