---
title: "Tell politicians what we know about good decision making"
date: 2013-12-19
categories: ["President's Column"]
---

Recently I was asked to give a lecture about decision making for a governmental committee that assesses furlough requests of delinquents with a preventive detention, to advise the minister of Safety and Justice. 
Since in my Presidential Address in Barcelona I had told all of us that we should tell politicians what we know about good decision making, I accepted. After a period of panic because of the audience (Important People: psychiatrists, judges) and because the topic was so general (Decision making: what to say? how to limit myself?) I decided to tell them the following.

Decision makers are expected to follow normatively correct rules of probability and logic, but they most probably rather follow psycho-logic. Examples are rife: people are often inconsistent, they take irrelevant information into account, see too many ‘special cases’, often do not learn from feedback, are influenced by recent experiences, and get tired and bored.
Furtive laughter from a captive audience; stupid people! Other people, yes maybe, but you are not talking about us surely! 

Then I presented them with some classic decision problems, such as the Linda problem and the Asian disease, asking for their judgments. That silenced them. I explained that they were excused, since that is what people’s mental make-up looks like – we need to use heuristics to allow us to cope with our complex environment.  Also I pointed out that these problems were not completely fair – how can you not use the representativeness heuristic: Linda is obviously not just a dull bank clerk; how can you not be influenced by frames: who wants to send hundreds of people to their deaths? 
I quoted Freud, who, according to the psychoanalyst Theodor Reik, had once told him that for decisions of minor importance, he always found it useful to weigh all pros and cons. In matters of vital importance however, such as the choice of a partner or profession, he thought the decision needs to come from the unconscious, from somewhere within. 

Indeed, the audience approved, that is how it is with people. You can make lists of pros and cons, but in your personal life you will still decide what feels good. 

Then I showed how Darwin had decided to marry. He made two lists, one in favour of marriage and one against. In favour was the possibility of having children, having a companion, musical entertainment that is good for your mood. Against were things such as no freedom, forced visits to in-laws, and loss of time. In the end the list of pros was longer than that of against, and he decided to marry. Ironically the marriage was quite unhappy. 

I proposed that from a human perspective, we obviously cannot avoid using intuitions. Indeed, many in the audience were eager to report instances in which they had relied on their intuitions. They saw a delinquent, and immediately knew what to decide. They felt rather proud of themselves at that point.

They again became a bit more modest after Frederick’s Cognitive Reflection Test. It took some people quite some time to realise that a ball cannot cost 10 cents when the bat and ball together cost $1,10 and the bat costs $1,00 more than the ball; some don’t believe it to this day. 
I told them that this illustrates that we tend to use our intuition first, and only sometimes, when forced or upon second thought, correct our intuitions by reflection. But also that in many instances our immediate initial response is flawed.

We discussed intuition, and I convinced them (I hope ☺) that intuitions can be correct – provided they are well learned, in Robin Hogarth’s Kind Environment.  Dangers should however not be underestimated: tunnel vision, overconfidence, and premature closure. But then again reflecting can also lead to wrong conclusions, so inaccuracy is not the prerogative of intuition.

Since they decide in a group, I showed them the two views on team decision making: Two heads are better than one; versus A camel is a horse designed by a committee. I pointed out dangers of groupthink and unthinkingly follow authority (Milgram being a case in point) versus profiting from the knowledge of your superiors. The bottom-line was that it is always best not to be prejudiced, not to overestimate your own decision making skills, to remain alert and to know the pitfalls, including your personal biases.

Why am I telling you all this? To remind us all that this is what we can and should do: tell policy makers what we know about the problems with decision making. 

I am not overconfident that they will take all our warnings to heart. These psychiatrists and judges will still defer to the group, they will still advise more negatively about somebody who has tattoos of bimbo’s on his forceps than about a shy mister Nobody, they will base their decision on what they did previously with a similar delinquent – but maybe, just maybe they may sometimes think twice.
If we succeed in making some policy makers think twice before they make their decision errors, that might save lots of money and sometimes lives. Although that is probably arrogant, it does keep us focused.

So keep up the good work, and let the whole world know about it!

Cilia Witteman
December, 2013

