---
title: "The future of EADM: Four years later"
date: 2013-05-23
categories: ["President's Column"]
---

Written by Nicolao Bonini

<b></b>Following SPUDM in Warsaw, Robin Hogarth addressed, in the first Presidential column, the issue of what EADM can do besides supporting SPUDM conferences. The three long-term goals that he listed all relate to how to “increase the image of decision research in Europe – to have positive effects on research funding, academic positions, and influence that reflects our unique knowledge”. There follow some comments and proposals.

1. <i>Funding of research / teaching initiatives</i>. This, I think, is a crucial aspect. We should do our best to foster initiatives among EADM members. One way to do so is use national funding allocated to support international cooperation (e.g. to support foreign principal investigators, incoming visiting scholars or students). Another way is to take advantage of European programmes - some are designed to strengthen relationships with extra-European countries. Those programmes could support research networks, but also European master courses, summer schools, or joint doctoral programmes. Posting news, announcing calls, or requesting collaboration on our webpage is a way to make EADM members aware of those opportunities (in Kingston-upon-Thames, the Board decided to hire a web-content manager who could also attend to these aspects). However, greater participation is needed to keep our website alive and updated. I wonder if we could do more. For example, appoint an EADM representative who would attend inception meetings at relevant European institutions, taking a propositive role as well as informing EADM members about discussions at those meetings that might be of relevance for J/DM scientists.

2. <i>Decision research community</i>. In the 1960s, there was a distinct European response to the growing interest in decision research, and SPUDM was its main manifestation. An article by Charles Vlek on “A Brief History of SPUDM” will be soon published on our website; future articles/comments will be welcome. We should do more to enhance our identity: not only for the benefit of young students but also for those not in academia (e.g., inform politicians and policy makers about competences available in our community – see next point). We are still collecting material, such as pictures and SPUDM programmes, that will be uploaded on our website. The aim is to give a pictorial history of that initiative and early ideas. All EADM members are encouraged to participate by sending relevant material to Michael Schulte-Mecklenbeck.

3. <i>Beyond academia</i>. I recall discussions with Maule, Hogarth and members of the Board/Association on how to improve the image of our research community outside academia. One suggestion was to use PR to publicize SPUDM and EADM workshops to a broader audience. This is certainly something that should be done. Let me share with you the experience of organizing SPUDM in Rovereto. We made an effort to publicize it widely (e.g., coverage in national newspapers, and national broadcasting of interviews with invited speakers). I believe that there was a substantive return on this effort. I came into contact with people from other disciplines, as well as with policy makers and various stakeholders. This could be done more systematically by a professional PR hired to publicize EADM members’ work, as was suggested many years ago. Alternatively, we could recruit a young scientist with good writing skills who could write regular J/DM research digests1.We could also try to create positive synergies with our sister society, the Society for Judgment and Decision Making, by, for example, organizing a joint EADM-SJDM workshop on “hot” topics that might also be of interest to the general public.

There are many things to do, and many others not yet thought of! So, please, do not hesitate to use our webpage (or to contact me or members of the Board) to offer your comments and your assistance.

Note 1: Thanks to Gaelle for suggestion.
