---
title: "The future of EADM "
date: 2013-05-23
categories: ["President's Column"]
---

Written by Robin Hogarth
<p align="justify">As a professional organization, EADM is a strange animal. It comes to life every two years for the SPUDM conference and then essentially hibernates in the interim. In fact, SPUDM predates EADM and it is important to recall that EADM was created to ensure the continuity of SPUDM conferences. So perhaps that’s all it should do?</p>
<p align="justify">And yet, several members feel that EADM should be more than just a support for SPUDM. Some question – with no little justification – the return they get for their annual membership dues. After all, SPUDM conferences are supposed to be self-financing.</p>
<p align="justify">Last year, as President of EADM, John Maule instigated a series of reflections on this topic amongst the EADM board members. As your new President, I reported on the substance of these discussions at the recent business meeting in Warsaw at SPUDM 21. However, few members attended the business meeting – and since I feel that we had some important things to say – I am taking this opportunity to report on what we said and to solicit your aid.</p>
<p align="justify">Attendance at SPUDM conferences – as well as the high quality of the many contributions – attests to the interest and talent for decision making research in Europe. However, this talent and interest is not matched by institutional support. One reason, I feel, is that we are all so busy doing our own “thing” that we fail to see how we can create synergies for all. For example, we miss out collectively on the many individual successes of our members. I strongly believe that when one of our members is successful professionally we should all rejoice in the achievement and literally take and enjoy some of the credit. A further important problem is that we lack information about what is going on in different parts of Europe and people from outside our organization have very little idea about what we do.</p>
<p align="justify">Given these issues, let me be more concrete and specify what the Board considers long-term goals for EADM that go beyond just supporting SPUDM conferences. There are three main goals:</p>

<div align="justify">
<ol>
	<li>To create more opportunities for research funding for our members. Currently, this is difficult because each country in Europe jealously deals with its own funding and we need to compete with established disciplines. However, with the advent of the new European Research Council that hopes to operate like the National Science Foundation in the US, things might change – see <a title="http://www.sciencemag.org/cgi/content/full/313/5792/1371" href="http://www.sciencemag.org/cgi/content/full/313/5792/1371">http://www.sciencemag.org/cgi/content/full/313/5792/1371</a>. Clearly, EADM must be aware of what is going on here and be prepared to intervene if necessary, e.g., in the short-term let the ERC know that we exist!</li>
	<li>To create positions in academic and related institutions for decision researchers. As anyone involved in placing recent PhD’s on the academic job market knows, Europe is not a seller’s market. There are many barriers and difficulties that result from both our nationalistic tendencies and the lack of regular decision making positions in academic departments.</li>
	<li>To have the input of decision researchers in important policy decisions affecting our lives as European citizens. As you are no doubt aware, it is quite normal in many policy debates to seek the input of academic economists and sociologists. Moreover these social scientists are typically willing to provide opinions on issues where, in fact, the findings of decision research might be more relevant. Consider, for example, providing people with information about risks, product safety, and other related topics.</li>
</ol>
</div>
<p align="justify">In short, the goals of the Board are to increase the image of decision research in Europe – to have positive effects on research funding, academic positions, and influence that reflects our unique knowledge.</p>
<p align="justify">These goals were well-received by the few members who attended the business meeting in Warsaw but the real question is how to achieve them. In the short-term, several actions can be taken:</p>

<div align="justify">
<ol>
	<li>Initiate discussions with the new European Research Council. Your President has some contacts here and will follow up on this.</li>
	<li>Continue to fund small conferences such as we have been doing for the last two years. However, people sponsoring such conferences will be required to investigate their PR potential (see immediately below).</li>
	<li>Investigate ways in which EADM can use PR to publicize SPUDM, the small conferences, work done by EADM members, and any other newsworthy activities. John Maule’s son has a small PR firm in London and is willing to help us on this pro bono (the only cost is that he should be allowed to advertise EADM as one of his clients). Clearly we are at an early stage on this project – help is needed!</li>
	<li>Develop an attractive and active webpage. In today’s world, we believe this to be essential. The webpage should be something that members access on a regular basis, where you find up-to-date information about what research is going on, funding opportunities, job opportunities, interesting ideas for teaching, and so on. The list of topics is limited only by our lack of imagination. In short, the webpage should become a “living newsletter.” In early brainstorming on this idea, we also thought of having different access points for different people who might be interested in our webpage – members, university administrators, the general public… To move things forward, we have appointed GaëlleVillejoubert to lead a “task force” to develop a web that we can be proud of. So, if you have ideas, please contact Gaëlle. As President of EADM, I strongly believe that it is in our collective interest to allocate some of our budget to this project. The webpage is our face to the world.</li>
	<li>I also intend to discuss with Board members of our sister society, the Society for Judgment and Decision Making, whether there are any ways of creating positive synergies between our two organizations along the lines mentioned above.</li>
</ol>
</div>
<p align="justify">Finally, if you have any reactions to the above, please contact me or any of the Board members. Our goal is to promote decision research in Europe.</p>
