---
title: "Weighting value and fit in academia "
date: 2013-05-23
categories: ["President's Column", "Uncategorized"]
---

Written by Ilana Ritov

I would like to share with the readers my thoughts about three different issues I have recently been asked to consider and express my opinion about. I believe many of us encounter these questions, and some may have very different answers. The first issue involved hiring new faculty. Candidates were considered for a job opening in my department. As is so often the case, two leading candidates emerged. One of them is doing highly interesting work, and pursuing issues that seem to me important. The other's work is somewhat less exciting, but is considered to better fit the departmental "needs". I argued in favour of the former candidate, apparently weighting the intrinsic value of theresearch over and above the matching of the candidate's interests with those of the department.

The second issue concerned a paper submitted to the journal Judgment and Decision Making, in which I serve as an associate editor. I found the paper highly interesting, as did the other members of the editorial board who read it. However, doubts were raised whether this paper should be published in a JDM journal. The paper did not examine choices, but compared evaluations of health related issues across countries and expertise levels. The decision whether to accept the paper for publication clearly rests on consideration of quality (in this case interest) vs. fit.

Finally, another problem I had to consider recently is whether to allow a student in the conflict management program I chair to take, as an elective, a class about "urban planning from the perspective of sub-populations". The class would (hopefully) be stimulating and could provide a background that is relevant to some conflict management analyses, but it is not directly related to the core of the program. The student wanted to take the class because she was very interested in the topic. I thought this was a good enough reason, and approved her request.

Needless to say, the three problems are very different in many respects. However, thinking about these three problems simultaneously, I realized they all involve weighting of two major attributes: intrinsic value and fit. Intrinsic value, in our domain, typically refers to how interesting we find the object, be it a research program, an individual paper, or a specific class. The fit is the degree to which the topic matches some pre-defined domain characteristics. More precisely, we think of the extent to which the topic is close to the prototypical exemplar of a category with fussy boundaries.

One factor that has been shown to affect attribute weighting is 'evaluability'. The easier it is to evaluate an attribute the greater the weight it carries. Perhaps due to the interdisciplinary nature and vague boundaries of our field, it seems to me that we as JDM-researchers find quality easier to evaluate than fit. This suggests that I may have assigned too much weight to quality/interest relative to fit.

Do I overweight one attribute relative to the other? A quick search of the vast literature on attribute weighting did not yield any clear conclusions. Incoherent preferences related to changes in attribute weighting are abundant. However, perhaps due to some self-serving bias, I cannot easily think of another framing in which my preferences with respect to the choices described above would have been different.
