---
title: "Where would JDM research be without gambles? "
date: 2014-07-03
categories: ["President's Column"]
---

At JDM workshops or conferences, we are all supposed to be gamblers.  We are asked: Would you prefer a gamble with a probability of .7 to win € 75 and a probability of .3 to win € 235, or another one with a probability of .1 to win € 1000 and otherwise nothing? Would I prefer a gamble with a probability of .65 to win € 75 and a probability of .25 to win € 235, or another one with a probability of .15 to win € 1000 and otherwise nothing?

I would prefer neither. With most of these talks, if I do attend, I doze off. I think they are artificial tasks, with no links to the real world, at least not mine. Why not ask whether I prefer orange juice or beer? Whether I would choose a blind date with a bald-headed artist or a long-haired academic? That would say something about me. You could ask for my arguments, track my eyes while I am comparing the options, and find out what I pay attention to and what decision strategy I use. Ask many people, and you get really usable and interesting information.

I don’t choose between monetary gambles. Don’t I, indeed? To be honest I do: I deliberate about taking out travel insurance. Like many other people, I prefer certainty to gambles. If I take the insurance, I want to pay just enough that I am certain that I will win out if I have to claim. But often no such certainty can be had, and I tend to travel un-insured. The lack of certainty is manifest especially in health care. Let me illustrate this with a real world example (violating the rule that you should not argue from your own experience, or use “I know somebody who” arguments – but who is going to stop me!, and I hope you recognize one of your own dilemmas).

I once saw a tuberculosis consultant, with who I had the following conversation: Consultant: your test, which we asked you to come in for because somebody in your vicinity was found to have active TB, was positive. So take these pills for the next month, and do not combine them with alcohol or any other drug. Me: What does that mean: my test was positive? Consultant: That means that you have anti-bodies to TB, which suggests that you may have latent TB. Me: If you say ‘suggests that you may’, what chances are you talking about, how likely is it that I actually have it? Consultant: You do not have it now, and the anti-bodies may be the result of an earlier exposure to TB; the chances that you will develop it given this positive test are 5 %. Me: That is a low chance of a future event. And what do these pills do, are they any good at lowering those chances? Consultant: They are not foolproof; it is estimated that they lower the chances by 20 %. Me: So from 5 % to 4 %? Consultant (losing his composure): It would seem so, yes. Me: And are there any side effects of these pills? Consultant (sighing when realising I was a ‘difficult’ case): Yes there are possible side effects, some rather serious. He got quite uncomfortable, so I chose not to ask for specific details of the chances of each of the side effects, but announced my decision that I would not take the pills. He exclaimed: But everybody with a positive test takes them! As if that would convince me. After some more discussion he gave in, and agreed that not taking them was quite sensible, and that if I ever felt symptoms, there was still time enough to start taking them. I felt bad, for him, for being stubborn, for pretending to know better; but mostly I felt good, for not taking unnecessary medication. (For those of you who like closure: no signs of TB now, 20 years later (yet J)).

Is this gambling? The opposite: calculating, I would say. Gambling with my health, doctors would say. Am I risk averse or risk seeking? I would say the first, doctors would say the second. Interesting! What would you have done? Now if JDM researchers would study this type of gamble, their talks at conferences would be so much more interesting!

Maybe I’m stretching it. But you must admit: this is about real things, real choices (even though many people would not experience it as a choice, but just take those pills). We can find out about the probabilities of each outcome. So we can construct gambles that are not artificial, but that are about actual choices. Would we prefer to have chemo with a 70% chance of success and a 30 % chance of very serious side effects, or an operation with a 60 % chance of a cure and 40 % chance of death? As a mother, what would you prefer for your very sick child? This is the type of gamble that unfortunately many people today are faced with. It is also the type of gamble discussed at medical decision making conferences, where they present results of studies with real people facing real dilemmas. It would be a relief to hear such talks at JDM conferences and workshops too, instead of talks about winning or losing hypothetical money. You would want to know what type of people would make which choice, and why. Interesting! I would go to all those talks, and stay awake.

&nbsp;

Cilia Witteman
July 3<sup>rd</sup> 2014
