---
title: "The EADM Interview: Adele Diedrich, Professor"
date: 2014-07-31
categories: ["EADM Interview"]
---

<p style="text-align: justify;"><strong>Who are you, and what do you do?</strong></p>
<p style="text-align: justify;">I am Adele Diederich, Doctor of Philosophy, and Professor of Cognitive Psychology at Jacobs University, Bremen, Germany. As typical for German universities, my position includes teaching and research. The main topic of my research is the study of information processing in various psychological contexts. I have worked, in particular, on sensory processes in perception and higher cognitive processes in decision making. My approach includes both the development of theories and models and their testing by experiment and empirical observation. In decision making I develop models for multiattribute decision problems which take into account both the dynamic and stochastic nature of decision making. My goal is to describe the motivational and cognitive mechanisms that guide the deliberation process in decisions.  I’m interested in why preferences waver over time and how long it takes to come up with a decision; how time pressure influences the decision; how conflict in multiattribute decision is solved; and how preference reversals can be explained by a dynamic approach. More applied research centers around prioritization in medicine. This is very different from basic research since politics also plays a role. Another area focuses on multisensory interaction, that is, the interaction of different modalities (vision, audition, touch) in space and in time. This research is inspired by neurophysiological evidence and might be of less interest to the JDM community.</p>
<p style="text-align: justify;"><strong>What do you consider your most important research tool(s) on your computer?</strong></p>
<p style="text-align: justify;"> I’m a modeler, that is I develop models that are rather complex. Without my <a href="http://www.mathworks.de/products/matlab/">Matlab</a> (this is computational software) I would be lost. It does all the parameter estimations which could not be performed by “hand”. Another very important tool is the search machine for finding articles on related work. Electronic access to all the data bases like <a href="https://sub3.webofknowledge.com/error/Error?PathInfo=%2F&amp;Alias=WOK5&amp;Domain=.webofknowledge.com&amp;Src=IP&amp;RouterURL=https%3A%2F%2Fwww.webofknowledge.com%2F&amp;Error=IPError">Web of Science </a>makes work so much easier and efficient.</p>
<p style="text-align: justify;"><strong>What do you consider your most important research tool(s) outside of your computer?</strong></p>
<p style="text-align: justify;">This is definitely the laboratory. All the models I develop are tested in rigorous experiments in the lab. Since I’m interested in choices and decision times we need to collect choice frequencies and choice response times. And I also record eye movements. The experiments need to be highly controlled. This would be very difficult to do in the field. However, for decision making in the medical context, I apply (web based) questionnaires as well.</p>
<p style="text-align: justify;"><strong>What is your favorite tip for getting writing done?</strong></p>
<p style="text-align: justify;">If you have a lot of other duties, like teaching and administration, try to reserve, if possible, at least one entire day of the week for writing, without interruption by students, meetings, or emails.</p>
