---
title: "Past Conferences"
---

Members of the Organizing Committees of SPUDM Conferences:
<table width="429" border="0" cellspacing="0" cellpadding="0"><colgroup> <col width="39" /> <col width="91" /> <col width="299" /></colgroup>
<tbody>
<tr>
<td align="right" width="39" height="29"><strong>2013</strong></td>
<td width="91"><strong>Barcelona</strong></td>
<td width="299">Elena Reustkaja, Mario Capizzani, Franz Heukamp, Robin Hogarth</td>
</tr>
<tr>
<td align="right" width="39" height="21"><strong>2011</strong></td>
<td width="91"><strong>Kingston</strong></td>
<td width="299">Gaëlle Villejoubert</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>2009</strong></td>
<td width="91"><strong>Rovereto</strong></td>
<td width="299">Nicolao Bonini, Dinos Hadjichristidis, Rob Ranyard, Elke Weber, Gaëlle Villejoubert</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>2007</strong></td>
<td width="91"><strong>Warsaw</strong></td>
<td width="299">Joanna Sokolowska, Tomasz Zaleskiewicz, Craig Fox, Nicolao Bonini</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>2005</strong></td>
<td width="91"><strong>Stockholm</strong></td>
<td width="299">Tommy Gärling, Henry Montgomery, Lisa Ordonez, Joanna Sokolowska, Danielle Timmermans</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>2003</strong></td>
<td width="91"><strong>Zürich</strong></td>
<td width="299">Roland Scholz, Renate Schubert, David Budescu, Tommy Gärling</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>2001</strong></td>
<td width="91"><strong>Amsterdam</strong></td>
<td width="299">Pieter Koele, Joop van der Pligt, Jeryl Mumpower, Renate Schubert</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1999</strong></td>
<td width="91"><strong>Mannheim</strong></td>
<td width="299">Martin Weber, José Kerstholt, Joop van der Pligt, George Wu</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1997</strong></td>
<td width="91"><strong>Leeds</strong></td>
<td width="299">John Maule, Rob Ranyard, Martin Weber, Eric Johnson</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1995</strong></td>
<td width="91"><strong>Jerusalem</strong></td>
<td width="299">Maya Bar-Hillel, Ruth Beyth-Marom, David Budescu, John Maule, Richard Thaler</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1993</strong></td>
<td width="91"><strong>Aix-en-Provence</strong></td>
<td width="299">Jean-Paul Caverni, Maya Bar-Hillel, Hutton Barron, Oswald Huber, Helmut Jungermann, Helen Moshkovich, Joop van der Pligt</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1991</strong></td>
<td width="91"><strong>Fribourg</strong></td>
<td width="299">Oswald Huber, Katrin Borcherding, Klara Farago, Oleg Larichev, Jeryl Mumpower, Joop van der Pligt</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1989</strong></td>
<td width="91"><strong>Moscow</strong></td>
<td width="299">Oleg Larichev, Katrin Borcherding, Istvan Kiss, David Messick, Stephen Watson</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1987</strong></td>
<td width="91"><strong>Cambridge</strong></td>
<td width="299">Stephen Watson, Istvan Kiss, Lola Lopes, Bernd Rohrmann, Willem-Albert Wagenaar, Stuart Wooler</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1985</strong></td>
<td width="91"><strong>Helsinki</strong></td>
<td width="299">Guje Sevón, Berndt Brehmer, Helmut Jungermann, Oleg Larichev, Peter Lourens, Gordon Pitz</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1983</strong></td>
<td width="91"><strong>Groningen</strong></td>
<td width="299">Charles Vlek, Katrin Borcherding, Berndt Brehmer, Baruch Fischhoff, Pieter Koele, Peter Lourens, Anna Vári</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1981</strong></td>
<td width="91"><strong>Budapest</strong></td>
<td width="299">Tibor Engländer, Anna Vári, Patrick Humphreys, Ola Svenson, Willem A. Wagenaar, Detlov von Winterfeldt</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1979</strong></td>
<td width="91"><strong>Göteborg</strong></td>
<td width="299">Lennart Sjöberg, Lee Roy Beach, Patrick Humphreys, Ola Svenson, Tadeusz Tyszka</td>
</tr>
<tr>
<td align="right" width="39" height="43"><strong>1977</strong></td>
<td width="91"><strong>Warsaw</strong></td>
<td width="299">Józef Kozielecki, Wojciech Gasparski, Helmut Jungermann, Lennart Sjöberg, James Wise, Gerard de Zeeuw</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1975</strong></td>
<td width="91"><strong>Darmstadt</strong></td>
<td width="299">Helmut Jungermann, Józef Kozielecki, Sarah Lichtenstein, Gerard de Zeeuw</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1973</strong></td>
<td width="91"><strong>Rome</strong></td>
<td width="299">Bruno de Finetti, Gernot Kleiter, Carl-Axel Staël von Holstein, Charles Vlek, Dirk Wendt</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1971</strong></td>
<td width="91"><strong>Uxbridge (London)</strong></td>
<td width="299">Larry Phillips, John Kidd, Sandy Lovie</td>
</tr>
<tr>
<td align="right" width="39" height="29"><strong>1970</strong></td>
<td width="91"><strong>Amsterdam</strong></td>
<td width="299">Gerard de Zeeuw, Charles Vlek, Willem Albert Wagenaar, Kiek van der Meer</td>
</tr>
<tr>
<td align="right" width="39" height="28"><strong>1969</strong></td>
<td width="91"><strong>Hamburg</strong></td>
<td width="299">Dirk Wendt, Carl-Axel Staël von Holstein, Charles Vlek</td>
</tr>
</tbody>
</table>
