---
title: "Jane Beattie Memorial Travel Scholarship"
---

<em><strong>For travel from Europe to the United States or from the United States to Europe</strong></em>

On behalf of both the Society for Judgment and Decision Making and the European Association for Decision Making, we invite applications for awards from the Jane Beattie Memorial Fund
<p align="justify">The Beattie Scholarship is now sponsored jointly by the Society for Judgment and Decision Making and the European Association for Decision Making. On behalf of both organizations, we again invite applications for awards from the Jane Beattie Memorial Fund. This fund was established in memory of SJDM and EADM member Jane Beattie and her contributions to judgment and decision research.</p>
The purpose of the fund is to provide scholarships to subsidize travel to North America or Europe for purposes of scholarly activity by a foreign scholar in the area of judgment and decision research, broadly defined. Attendance at the annual SJDM meeting or SPUDM meeting is one example of an activity that would be appropriate for support, but by no means the only one. All scholars outside of the destination are eligible to apply.

Note that EADM is sponsoring awards made to its members (including student members), so applicants should please be sure to indicate if they EADM members.

&nbsp;
