---
title: "Workshop 2009: Environmental Decisions: Risks and Uncertainties"
---

<h1>Environmental Decisions: Risks and Uncertainties</h1>
To improve the decision making process related to environmental problems, it is important to understand individual and collective environmental risks and uncertainties. This involves studying the assessment, perception, management and governance of risks. These four different fields involved in environmental decision making use, however, different definitions and notions of risk without much exchange between the researchers in the various areas. Therefore, it is difficult for a given field to adapt to profit from the methods and outcomes used in other fields.

Environmental decision making is a complex process. The main goal of the conference was to cope with this complexity by stimulating interdisciplinary work between scholars working in the fields of risk governance, management, perception, and assessment.

<!--StartFragment-->

<em>Structure</em>

The conference consisted of four pillars: risk assessment, risk perception, risk management and risk governance. In parallel workshops, each pillar focused on theoretical and applied issues linked to environmental problems. In addition, the four pillars were merged in two types of plenary sessions. There were ten keynote speakers giving an overview of specific topics as well as over-arching environmental decision making topics. Furthermore, all participants discussed the possibilities of bonding the four research fields during plenary discussions.

<em>Results</em>

The ten invited speakers from various internationally known institutes discussed the latest findings within their specific research field. Their talks provided a variety of insights on environmental decision making, ranging from fundamental discussions about definitions of risks and uncertainty (Terje Aven and Robert Chambers) to integration frameworks, such as the International Programme on Integrated Research on Disaster Risk (Richard Eiser) and the International Risk Governance Framework (Marie Valentine Florin). Other keynote speeches covered practical experiences with risk assessment (Dennis Paustenbach), scientific studies on lay peole’s perception of climate change (Helmut Jungermann), decision making aids (JosephArvai) or political aspects related to environmental decision making (Kenneth Oye). Last, but not least, uncertainties were looked at from different viewpoints: system analysis (Wolfgang Kröger), organisational behaviour (Gudela Grote), and economics (Robert Chambers).

At the end of the first day, a first attempt to integrate the four risk research fields was made by defining overarching issues to be solved for integration purposes. The following aspects turned out to be relevant: We need common definitions of risk. (“Risk is a common currency to us.” Who is exposed to risks? Which risks are acceptable? What are uncertainty and “high quality” decisions?). We should look at different actors’ perspectives in our research (i.e., who has which interests, and who has costs and/or benefits?). What is the time frame for the decision? To what extend can we use existing integrative models? Are there alternatives? The discussion resulted in four questions that each of the pillars was asked to answer during the next days of the workshop: 1) what do we expect/need from other pillars? 2) what can we offer to other pillars?, 3) why is there so little integration?, and 4) how to overcome the integration barriers?

The following two days were mainly reserved for four parallel pillar-related workshops. The presentations during the risk assessment workshop focused on three topics: 1) reordering the risk modelling framework, 2) how risk assessment can support environmental decision making in specific cases (e.g. radioactive waste problemor nuclear safety), and 3) risk assessment of engineered nanomaterial. The risk assessment pillar suggested aligning the risk definitions of decision theory (risk is the evaluation of uncertain losses) with the toxicological tradition (risks is exposure * sensitivity). The participants of this workshop wanted decision makers and assessment scientists to learn from each other. Therefore, the exchange of preferences, weights and blind spots of decision makers should be included in the frameworks, process formations and results of the assessment scientists.

The Risk Governance pillar discussed how institutional designs (e.g. governance systems) dealt with various environmental decisions and the effectiveness of these designs under certain conditions. Examples of such conditions were uncertainty, asymmetric information and power differences. The workshop concentrated on the design of effective and stable institutions that are, at the same time, flexible towards changing social problems. Solutions for dilemma situations (e.g. economical efficiency vs. effectiveness) were elaborated. With respect to the integration of risk research, the gap between lay people’s perception and experts’ perception o frisks, and the lack of convergent risk assessment standards were identified as barriers. Increasing international trade (i.e. globalisation) could be helpful.

In the risk management workshop, three topics were in the centre of the presentations: 1) managing ecosystems based on thresholds between ecosystem switches, 2) climate policy under uncertainty: cost-benefit tradeoffs over time and 3) risk management strategies to deal with extreme weather events in agriculture.  The pillar identified several types of inputs needed from other pillars.  Important elements are information about potential non-stationarity of time series, information about public perception of thresholds and about investments overtime, and information about the barriers to implement economic policies and integrate risk management insights into policy processes.

The participants of the risk perception pillar worked on three themes: 1) the development of a comprehensive framework to explain how laypeople perceive risks, 2) getting an overview of risk communication strategies and how these fit to developments in social and cognitive psychology, risk governance, management and assessment and 3) the public’s perception of climate change. The pillar concluded that it can offer to other environmental decision-making research fields knowledge about how laypeople perceive risks (i.e. why laypeople hardly perceive climate change as a problem), about communication of risks, and about data on factual behaviour to improve exposure modelling. Risk perception researchers should however promote their work much more. It was suggested to form integrated research teams for specific environmental problems.

This last suggestion was adopted by other pillars: more integrated workshops or programmes are needed to build up relations among researchers from the various environmental decision-making research fields. Topic related problem solving workgroups should be and stakeholders from various disciplines should take part in such workgroups.

<em>Sponsors</em>

We would like to thank the Centro Stefano Franscini (CSF), the Swiss Academy of Humanities and Social Sciences (SAGW), Cogito Foundation, Swiss Federal Office for Energie (BfE), the European Association for Decision Making (EADM) and Swiss Hail Insurance Association for their financial support, which enabled us to organize this conference.
