---
title: "Workshop 2012: EGPROC, Bolton"
---

<h1>European Group of Process Tracing Studies</h1>
<b>EGPROC, Bolton, May 2012</b>

EGPROC (European Group of Process Tracing Studies) is unusual, perhaps unique, as an organization in sustaining a series of annual meetings for 30 years without a formal structure: no constitution, committee or officers. Members take turns in hosting the meeting in their home city or university. The primary interests of the group are in process tracing methods and theory in the fields of judgment and decision making. The 2012 meeting was held at the beginning of May in the University of Bolton in England. It was organized by Rob Ranyard (one of the original members of EGPROC) from the Economic Psychology and Decision Research Group in the University of Bolton and Olga Kostopoulou of King’s College London, with financial support from EDAM. For the programme and abstracts see <cite><a href="http://www.egproc.org/wp-content/uploads/2012/05/Programme2012.pdf">www.egproc.org/wp-content/uploads/2012/05/Programme2012.pdf</a>.</cite> There were 36 participants; the programme comprised an Introduction by Ola Svenson, three invited talks (Jay Russo &amp; Anne-Sophie Chaxel; Andreas Glöckner; Edward Cokeley), 12 sessions, a ‘plenary’ session led by Michael Schulte-Mecklenbeck and Ola Svenson, with invited discussant Cilia Witteman, and five poster presentations.

The meeting demonstrated features that have characterized the group since its inception: focused discussion (no parallel sessions and ample time for discussion following presentations); speakers are encouraged to present ‘work in progress’ and fresh studies and data rather than published work; there is an emphasis on experimental tests of hypotheses generated from theory. Both pre-decision and post-decision processes were investigated and a range of process tracing methods was utilized including think-aloud protocols, information search patterns, for example with eye-movement tracking or MouselabWEB, and reaction-time measures. Research was conducted in both laboratory sessions and in more applied settings, the latter including consumer behaviour, participants’ evaluations of medical and psychotherapeutic treatments, and doctors’ diagnostic reasoning as well as judgments in the moral and political realms. The influence of individual differences was studied, for example variation in psychometric measures of general ability and numeracy. The potential for application of research to decision support systems was considered.

The laboratory-based studies show that research continues to make use of the gamble of the typical form ‘win A with probability p or lose B with probability q’ which was originally introduced to decision research as a means of measuring utility but which is still ‘mined’ for evidence of cognitive re-structuring, decision rules, strategies, heuristics, intuitions and so on, and to study the effects of variation of forms of task presentation. There is on-going interest in cognitive biases although this group aims to go beyond demonstrating them in order to relate them to information processing and to more general goals, for example in pursuit of coherence (Glöckner <i>et al</i>.), consistency (Russo &amp; Chaxel) or risk avoidance (Oswald Huber <i>et al</i>.). Research has identified a multiplicity of compensatory and non-compensatory rules, strategies and heuristics that are detectable by process tracing methods and this represents an important step in understanding the cognitive representations and operations involved in judgment and decision making.

Nevertheless, as was evident in the presentations and discussion sections, there remain challenges for theorists and researchers. Can we identify with precision the factors that predispose people to adopt specific strategies in particular circumstances given that they are sensitive to task demands and forms of presentation of information, a key issue in Glöckner’s talk? What is the validity of process tracing methodology, an important theme in talks given by Anton Kühberger, Michael Schulte-Mecklenbeck and, from a somewhat different perspective, Gaelle Villejoubert? As a final thought about a future direction for research, the researchers here have the concepts and tools to make a significant contribution to the psychology of the economic crisis that has engulfed Europe and the rest of the world since the banking failures of 2008, a crisis which most of us find difficult to understand!

I found this a stimulating and enjoyable meeting, its sessions characterized by high quality talks which encourage argument and constructive criticism in an open and informal environment. This includes the presentations I have not had space to mention here. The 2013 meeting is planned for Warsaw and relevant information will be available on the EGPROC web site, <a href="http://www.egproc.org/">http://www.egproc.org/</a>.
