---
title: "Workshop grants"
---

To stimulate activities in the two-year gap between SPUDM conferences, EADM sponsors up to two workshops or similar events per year, up to a maximum of EUR 3,000; to be decided upon per proposal. Proposals with applications for funding can be sent to the EADM Treasurer, Bernd Figner via email. 
 
The workshop has to meet the following requirements:
<ol>
	<li>The main organiser of the event must be a full EADM member.</li>
	<li>The meeting should be advertised on the EADM website and the EADM mailing list.</li>
	<li>EADM members should be offered a reduced fee for attendance.</li>
	<li>The organisers of the meeting should acknowledge the financial support of EADM in their advertisements and publications.</li>
	<li>The meeting should in principle be open to EADM members at a reduced fee, but the local organiser has the final say about the maximum number of participants.</li>
	<li>The organiser should submit a budget to the treasurer of EADM, clearly indicating how the EADM money will be used.</li>
	<li>A report about the meeting, containing at least the abstracts of presented (main) papers, must be published in the EADM website.</li>
</ol>

Direct your application for funding a workshop to the <a href="mailto:treasurer@eadm.eu">Treasurer</a> via email. <strong>Deadline for applications</strong> is January, 31st . A decision will be communicated after the board meeting mid-March of the same year. 

Applications should include the title of the workshop/event, provisional date, location, organisers, background, aims and objectives, provisional schedule, itemised budget, additional sources of support, references. 
