---
title: "Workshop 2010: Intuition: Methods and Recent Findings"
---

<h1>Intuition: Methods and Recent Findings</h1>
The aim of this workshop was to strengthen the theoretical and methodological foundations of the study of intuition in judgment and decision making, as a sequel to the publication of <a href="http://www.psypress.com/foundations-for-tracing-intuition-9781848720190">Foundations for Tracing Intuition</a>, edited by Andreas Glöckner and Cilia Witteman (Psychology Press, 2010). Many of the contributors to that book participated in this workshop, including those reviewers who contributed by being enthusiastic on the back cover of the book. There were some 35 participants, with 10 talks and 12 posters.

<!--StartFragment-->Andreas Glöckner, in his introductory talk, gave an overview of the methods currently most used to study intuition, and of the distinction of 4 types of intuition made in our book. He then discussed his favourite model: parallel constraint satisfaction – a model that most parsimoniously describes the different intuitive processes. In three invited talks, we then heard what happens when you intuit: you recognise rather than implement opportunities and it seems that managers’ ability to intuit is important for the success o fcompanies (Eugene Sadler-Smith), we learned that people perform better when problems are presented as sequentially simulated outcomes which allows learning from experience (Robin Hogarth), and we were informed that there sometimes seem to be advantages of “unconscious thinking” (Maarten Bos).

The posters were at least as interesting as the talks, and it was indeed very stimulating to read and discuss them in the sunny garden of the MPI building.

The topics of the afternoon talks were fluency (Sascha Topolinski), causal induction (York Hagmayer), truth (Christian Unkelbach), loss aversion (Eldad Yechiam), a reinforcement heuristic (Anja Achtziger) and mood and attitudes (Marieke De Vries); all in relation to a distinction between deliberate and intuitive processes. The workshop was concluded with a very lively discussion of, broadly, the advantage of using the term ‘intuition’ in psychological research and its subdivision in four types of underlying processes. Some in the group were very happy that ‘heuristics’ were not included in the categorisation, others would like to have seen it there. As was to be expected, we then ended up with definition issues. The general conclusion was that we are happy with the inclusion of scientific studies of intuitive processes, a recognition that intuition is not a uniform concept, and that more research is needed.

We want to thank EADM for its sponsoring and all attendees for their inspired and inspiring contribution.

Arndt Bröder, Andreas Glöckner &amp; Cilia Witteman
