---
title: "Lifetime Contribution Award"
---

The EADM Lifetime Contribution Award is bestowed in recognition of
lifetime contribution which is broadly considered as: Contribution to the decision-making community by “exceptional service to the community of decision-making researchers”, as broadly understood within the EADM tradition. This includes, but is not limited to the mentoring and supervising students and early career scholars who have proceeded to have independent, successful careers in the field; valorization of own or others research to have positive impact beyond the field (including other fields and/or policy and practice); and making a sustained and enduring contribution to EADM (e.g., through organization of EADM-related events including SPUDM and service to the JDM journal).

Eligible candidates need to be 20 years or more post-PhD and to have presented in SPUDM or other EADM events at least three times during the past 15 years.

Winners will receive a lifetime (free) membership in EADM, a certificate, and will be asked to make a presentation of their research or a historical perspective at SPUDM.

Importantly: Nomination is by the candidate or by another person on their behalf.
Submission requirements: For self-submissions, please send your CV and a 1-2 pages (maximum) justification letter. To submit the candidacy of another person please send just a 1-2 pages (maximum) justification letter.
<div></div>
<div></div>
<div>
<h1><strong>Former Winners</strong></h1>
<table border="0" cellpadding="5">
<tbody>
<tr>
<td><a href="/files/2025/11/Lifetime2025_Teigen.pdf">2025</a></td>
<td>Karl Halvor Teigen</td>
<td>University of Oslo, Norway</td>
</tr>
<tr>
<td>2023</td>
<td>Robin M. Hogarth</td>
<td>Universitat Pompeu Fabra, Spain</td>
</tr>
</tbody>
</table>
</div>
