---
title: "Jane Beattie Scientific Recognition Award"
---

In 2006, EADM created the Jane Beattie Scientific Recognition Award to honour the memory of our late colleague, Jane Beattie. The award is intended for researchers who have recently completed the first stages of their careers – defined operationally by those who are 5 to 10 years post-PhD. The award will be for a research paper that deals with the topic of decision making as broadly understood within the SPUDM tradition. 

The award is bestowed in recognition of “innovation in decision research”, as broadly understood within the SPUDM tradition. To be eligible for this award, candidates must have completed their PhDs no sooner than 5 years before the end of the most recent SPUDM meeting and no more than 10 years before the same date.

Winners will receive a prize of 1,000 euros, a certificate, and be asked to make a presentation of their research at SPUDM.

Submission requirements:  (a) a statement of 500 words or less that makes the case for the candidate’s innovation, (b) one paper in which the innovation is presented for a scientific audience, and (c) a copy of the candidate’s curriculum vitae. (d) Candidates should also provide a statement as to when, and from where they received their PhDs.

<strong>Winners</strong>

2023 - <strong>Lukasz Walasek</strong>, University of Warwick, Great Britain.

Committee: Eldad Yechiam (chair), Gaelle Vallee-Tourangeau, Michael Schulte-Mecklenbeck

2021 - <strong>Sudeep Bhatia</strong>, University of Pennsylvania, United States.

Committee: Ido Erev (chair), Shaul Shalvi, Mandeep Dhami, Bettina von Helversen, Thomas Wallsten

2019 - <strong>Shaul Shalvi</strong>, University of Amsterdam, The Netherlands.

Committee: Andreas Glöckner (chair), Mehdi Moussaid, Arndt Bröder, Peter Ayton, Cilia Witteman

2017 - <strong>Mehdi Moussaïd</strong>, Max Planck Institute for Human Development, Germany.

Committee: Barbara Summers (chair), Timothy J. Pleskac, Nigel Harvey, Eldad Yechiam

2015 - <strong>Timothy J. Pleskac</strong>, Max Planck Institute for Human Development, Germany.

Committee: Cilia Witteman (chair), Mirta Galesic, Fergus Bolger, Anton Kühberger

2013 - <strong>Mirta Galesic</strong>, Max Planck Institute for Human Development, Germany.

Committee: Nicolao Bonini (Chair), Fergus Bolger, Danny Oppenheimer and Barbara Fasolo.

2011 - <strong>Danny Oppenheimer</strong>, UCLA Anderson School of Management, United States.

Committee: Ilana Ritov (Chair), Marcel Zeelenberg, Ellen Peters and Nicolao Bonini.

2009 - <strong>Ellen Peters</strong>, Decision Research, Oregon, United States.

Committee: Robin Hogarth (Chair), Marcel Zeelenberg, Nigel Harvey, Ilana Ritov.

2007 - <strong>Marcel Zeelenberg</strong>, Tilburg University, The Netherlands.

Committee: Robin Hogarth (Chair), Nigel Harvey and Oswald Huber.

