---
title: "2018 Workshop on Clinical Decision Making"
date: 2018-04-03
categories: ["Conferences", "EADM Home"]
---

The theme of the workshop is “<em>Unravelling</em> the Clinical Process”.

The workshop brings together practitioners and researchers from medicine and psychology who are interested in the psychological processes underlying clinical reasoning and decision making. This includes research on the role of intuition and gut feelings in decision making, the interplay of deliberate and intuitive processes in diagnostic reasoning, the impact of causal reasoning on treatment planning, and many more exciting topics.

Invited and confirmed keynote speakers are Professor Nancy Kim, Northeastern University, Boston USA, Professor Wolfgang Gaissmaier, University of Konstanz, Germany, and Professor Norbert Donner-Banzhoff, University of Marburg, Germany.

For more information see on the workshop see
<a href="https://www.psych.uni-goettingen.de/en/conference/2018JCCM">https://www.psych.uni-goettingen.de/en/conference/2018JCCM</a>

The workshop is supported by the European Association for Decision Making (EADM), the Leibniz ScienceCampus Primate Cognition, and the University of Goettingen. There is no fee for participants.

<em>Local Organizers: </em>York Hagmayer (Institute of Psychology, University of Goettingen)<em> and </em>Johannes Hauswaldt (Department of Primary Care, Univer<em>sity Medical Center Goettingen)</em>
