---
title: "33rd Meeting of the European Group of Process Tracing Studies in Judgment and Decision Making"
date: 2014-03-27
categories: ["Conferences"]
---

We are pleased to announce the next EGPROC meeting (European Group of Process Tracing Studies in Judgment and Decision Making), to take place in Salzburg, Austria, from 1st May to 3rd May 2014.
The EGPROC conference is an annual meeting of researchers interested in process tracing research in JDM (eye-tracking, computerized tools capturing information search [like MouseLab, or mouse tracking], verbal protocols, skin conductance resistance, …). It has a long-standing tradition reaching back to 1982 and since then is a highly stimulating event of leading European researchers working with process tracing approaches in JDM and neighboring fields.
Two types of contributions will be accepted: (i) standard presentations of 45 minutes allowing for ample discussion; (ii) work-in-progress presentations of 15 minutes. For submitting a contribution, please write an e-mail to <a href="mailto:salzburg2014@egproc.org ">salzburg2014@egproc.org</a> containing the title of your presentation, your co-authors (if any), the type of submission (standard presentation; work-in-progess) and an abstract (max. 300 words) by 04th April 2014. We will quickly review your submission and get back to you within two work days.

Program
Besides of the main conference on Friday and Saturday, we are also holding a pre-conference workshop on eye-tracking , and (ii) a panel discussion on what qualifies as a process model. The pre-conference workshop on the use of eye-tracking in JDM research will be held on Thursday, 1st May. This workshop will provide hands-on experience on doing eye-tracking research and a discussion of relevant issues in eye-tracking. It will be jointly held by Dr. Benjamin Gagl (University of Salzburg) and Dr. Frank Renkewitz (University of Erfurt).
The meeting will also include a panel discussion, on Saturday, 3rd May, on what process models are and how to define them. Jana Jarecki from the MPI of Human Development (Berlin) will give the input presentation inviting discussion.
Updated information about the conference and the registration can be found at the <a href="http://www.egproc.org/egproc2014/egproc-2014-in-salzburg/">EGPROC homepage</a>. We will keep you informed using the EGPROC mailing list (if you are not a member of the mailing list yet, you can join in <a href="https://ml06.ispgateway.de/mailman/listinfo/egproc_egproc.org">here</a>).

We are looking forward to see you in Salzburg.

The Organizing Committee (Anton Kühberger &amp; Tom Scherndl)
