---
title: "4th EADM Summer School - announcement"
date: 2017-10-31
categories: ["Summer School"]
---

<div class=""><strong>SAVE THE DATE!</strong></div>
<div class=""><strong>Date: July 9th - 15th, 2018</strong></div>
<div class=""><strong>Location: University of Salzburg, Department of Psychology</strong></div>
<div class=""><strong>Theme: <span class="">Open Science in Decision Making Research </span></strong></div>
<div class=""><strong>Eligible: Pre- and early Post-Docs</strong></div>
<div class=""><strong>SAVE THE DATE!</strong></div>
<div class=""></div>
<div class="">The summer school has two main objectives:</div>
<div class="">1) Introducing and applying the ideas of open science, replicability and reproducibility in judgement and decision making research.</div>
<div class="">2) Providing an introduction to collecting and understanding process data in the realm of economic  experiments and consumer behavior.</div>
<div class=""></div>
<div class="">The summer school will include keynotes from:</div>
<a href="https://www.coll.mpg.de/team/page/susann_fiedler"><strong>Susann Fiedler</strong></a> (Max Planck Institute for Research on Collective Goods, Bonn)<br class="" /><a href="https://www.mpib-berlin.mpg.de/en/staff/ralph-hertwig"><strong>Ralph Hertwig</strong></a> (Max Planck Institute for Human Development, Berlin)
<a href="https://www.harding-center.mpg.de/en/persons/mirjam-jenny-0"><strong>Mirjam Jenny</strong></a> (Harding Center for Risk Literacy, Berlin)
<a href="https://www.wbs.ac.uk/about/person/neil-stewart"><strong>Neil Stewart</strong></a> (Warwick Business School, Warwick)
<div class=""><strong>Further details will be posted early 2018.</strong></div>
<div class=""><strong>Feel free to contact us at: <a href="mailto:summerschool2018@eadm.eu">summerschool2018@eadm.eu</a> or on Twitter <a href="https://twitter.com/eadmsummer">@eadmsummer</a></strong></div>
<div class=""></div>
