---
title: "Call for papers – SPUDM 26 – Technion, Israel"
date: 2017-01-23
categories: ["SPUDM"]
---

The European Association for Decision Making invites submissions for presentations, posters and/or symposia for its 2017 Biennial SPUDM 26 conference to be held at the Technion – the Israel Institute of Technology in Haifa, Israel, from Sunday August 20 to Thursday August 24, 2017.  

All submissions must be made electronically.

Invited keynote speakers:
Alvin E. Roth, Stanford University, USA
Debora Estrin, Cornell Tech, USA
Ido Erev, Technion, Israel
Presidential Address by EADM president:
Andreas Glöckner, Göttingen University, Germany
 

The conference focus will combine traditional topics as well as new directions in Judgment and Decision Making research.

More details and submission guidelines are available on the conference website -- <a href="https://spudm2017.net.technion.ac.il/call-for-papers/">https://spudm2017.net.technion.ac.il/call-for-papers/</a>

For further assistance please contact the organizing committee at <a href="mailto:spudm26@idc.ac.il">spudm26@idc.ac.il</a>

We are looking forward to welcoming you in Haifa.

 

SPUDM 26 organizing committee:

Shahar Ayal, IDC Herzelia
David Budescu, Fordham University
Ido Erev, Technion – Israel Institute of Technology
Andreas Glöckner, Göttingen University
Ilana Ritov, Hebrew University
Shaul Shalvi, University of Amsterdam
Richárd Szántó, Corvinus University of Budapest
