---
title: "Context-dependent consumer decision-making: An interdisciplinary inquiry"
date: 2013-08-26
categories: ["EADM Prizes"]
---

On June 17<sup>th</sup>, 2013, a one-day workshop entitled “Context-dependent consumer decision-making: An interdisciplinary inquiry” was held at the Department of Economics and Management (University of Trento, Italy). The meeting was jointly sponsored by the European Association of Decision Making and the Department of Economics and Management.

The workshop aimed to promote an interdisciplinary approach to the study of consumer decision-making with perspectives from psychology, (neuro)-marketing, behavioral economics, behavioral law and sociology. To that end, we conveyed invited speakers to discuss the theoretical, experimental and applied implications of the behavioral science of normal and abnormal consumer decision-making.

There were three keynote speakers: John Payne, Fuqua School of Business, Duke University (USA), Carolyn Yoon, Stephen M. Ross School of Business, University of Michigan (USA) and Barbara Fasolo, Department of Management, London School of Economics (UK). Also, there was an oral communication and poster session.

Payne addressed the role of context in consumer decision making by focusing on classic behavioral effects including his own pioneering studies on choice menu. Yoon presented the audience with an analysis of recent trends in consumer neurosciences, and an original study on brand neuro-marketing. Fasolo addressed the role of nudging consumers via the design of web-interfaces in the domain of health and tourism.

A selected group of oral communications followed. They addressed an aspect of the theme of the workshop. Also, a poster session took place.

For more detailed information on the content of the talks, and for those who are interested to download the slides, the University of Trento conference website is: <a href="http://events.unitn.it/aisc2013/workshop-context-dependent">http://events.unitn.it/aisc2013/workshop-context-dependent</a>

Slides are available <a href="http://events.unitn.it/aisc2013/workshop-context-dependent">here</a>

Schedule

9.30-17.30 – WORKSHOP – Room 2C – Monday 17/6

“Context-dependent consumer decision-making: An interdisciplinary enquiry”

9.20 Welcome  Nicolao Bonini (University of Trento)

9.30 -10.30 John Payne (Fuqua School of Business, Duke University, USA)

“How to decide: The Past and Future of Constructed Preferences”

10.30-11.30 Carolyn Yoon (Stephen M. Ross School of Business, University of Michigan, USA)

“The context-dependent nature of brand judgments: Insights from consumer neuroscience”

11.30-11.50 Coffee-break

11.50 12.50 Barbara Fasolo (Department of Management, London School of Economics, UK)

“Developing Adaptive Choice Architecture”

Lunch

14.15-15.15 Poster session (coffee-break room)

Buddhiprabha Pathirana, Evan Fradkin, Cinzia Giorgetta, Cinzia Calluso, Inga Jonaityte, Gianluca Finotti, Tokarchuk Oksana, Francesca De Petrillo, Andrea Galentino, Alessandro Grecucci, Andrea Rattin, Cesare Guerreschi, Alan G. Sanfey, Nicolao Bonini, Annalisa Tosoni, Giovanni Pezzulo, Giorgia Committeri, Riccardo Boero, Annalisa Garis, Marco Novarese, Maurizio Tirassa, Laura Vella, Ponsi, G., Delfino, A., Addessi, E., Paglieri Fabio, Xiaolei Zhou, Joseph G. Johnson

15.15-16.30 - Talks - Room 2C

15.15-15.40 Kim Kaivanto (Dept. of Economics, Lancaster University)

“Asymmetric Dominance and Compromise Effects as Manifestations of Choice Without Preference”.

15.40-16.05 Michele Graffeo, Luca Polonio, Nicolao Bonini (University of Trento)

“Looking for the best deal: How numeracy and reflexive thinking are associated with fast and slow processes”.

16.05-16.30 Michela Balconi, Beniamino Stumpo, Valeria Trezzi,Ylenia Canavesio (Catholic University of Milan; Foundation Research Organization GTechnology, Modena)

“Choice and preference in neuromarketing. Neuropsychological, autonomic and cognitive measures in response to different emotional-valenced products”.

16.30-16.50 Coffee-break

16.50-17.40 Talks 4/9

16.50 -17.15 Martina Reitmeier, Jutta Roosen (Dept. of Marketing and Consumer Research, Technische Universität München) “The impact of life transitions on food consumption decisions - Analysis of older consumers”

17.15-17.40 Giuseppe Bellantuono (University of Trento)

“Nudge policies everywhere?”

Additionally to the three keynotes and presenters (oral and poster communications) we had several participants who contributed to the discussion through all workshop works. Overall, slightly less than 50 participants took part at the workshop contributing to a deep interdisciplinary discussion on the role of context on consumer decision making. The represented disciplines ranged from psychology, economics, law, management, marketing, neurosciences, and sociology. We think that this accomplished the goal of promoting a deeper and multi-perspectives comprehension of complex phenomena such as that of consumer-decision making processes.

We thank the European Association for Decision Making (EADM), and the Department of Economics and Management for their financial support. The University of Trento (Conference Division), and the Italian Association of Cognitive Sciences (AISC) are also thanked for their organizational support.

&nbsp;

Scientific and Organization committee

Prof. Dr. Nicolao Bonini (Chairman), <a href="mailto:nicolao.bonini@unitn.it">nicolao.bonini@unitn.it</a>

Prof. Dr. Luigi Mittone, <a href="mailto:luigi.mittone@unitn.it">luigi.mittone@unitn.it</a>

Dr. Marco Cruciani, <a href="mailto:marco.cruciani@unitn.it">marco.cruciani@unitn.it</a> (AISC representative)

Prof. Dr. Umberto Martini, <a href="mailto:umberto.martini@unitn.it">umberto.martini@unitn.it</a>
