---
title: "EADM members join the JDM journal supervisory committee"
date: 2013-05-23
categories: ["News"]
---

The journal Judgment and Decision Making is now the joint journal of the Society for Judgment and Decision Making (SJDM) and the European Association for Decision Making. This means that it will be supervised by a committee consisting of two members representing each organization, appointed by the president of each. The supervisory committee has complete, ultimate control over all matters pertaining to the journal, although it is assumed that the editor (Jon Baron) will make day-to-day decisions and will consult the committee only for fairly major issues (such as changes in policy), or when he needs advice. SJDM has decided that it's executive board must approve the appointment of the next editor, after the committee makes a recommendation. The committee will consist of:
<ul>
	<li>Derek Koehler, University of Waterloo (SJDM)</li>
	<li>Gary McClelland, University of Colorado (SJDM)</li>
	<li>Cilia Witteman, Radboud University (EADM)</li>
	<li>Nicolao Bonini, University of Trento (EADM)</li>
</ul>
