---
title: "Judgment and Decision Making as a Skill"
date: 2013-05-22
categories: ["News"]
---

Recent publication from our member <a href="http://www.surrey.ac.uk/psychology/people/mandeep_dhami/">Mandeep Dhami</a>

This book presents a comprehensive review of emerging theories and research on the dynamic nature of human judgment and decision making (JDM). Leading researchers in the fields of JDM, cognitive development, human learning and neuroscience discuss short-term and long-term changes in JDM skills.

The authors consider how such skills increase and decline on a developmental scale in children, adolescents and the elderly; how they may be learned; and how JDM skills can be improved and aided. In addition, beyond these behavioral approaches to understanding JDM as a skill, the book provides fascinating new insights from recent evolutionary and neuropsychological approaches.

The authors identify opportunities for future research on the acquisition and changing nature of JDM. In a concluding chapter, eminent past presidents of the Society for Judgment and Decision Making provide personal reflections and perspectives on the notion of JDM as a dynamic skill.

Dhami, M. K., Schlottmann, A., &amp; Waldmann, M. (2011). Judgment and Decision Making as a Skill. Cambridge, UK: Cambridge University Press.

<a href="http://www.cambridge.org/gb/knowledge/isbn/item6478746/?site_locale=en_GB" target="_blank">http://www.cambridge.org/gb/knowledge/isbn/item6478746/?site_locale=en_GB</a>
