---
title: "Minutes, September 2nd, 2007, Warsaw, Poland "
date: 2013-07-09
categories: ["EADM Minutes"]
---

<h3></h3>
1. Opening by John Maule (president)

We currently have 166 senior and 28 PhD paying members.

2. Reports of the 2005 and 2006 Board and business meetings are presented to the members;

All members are now on the mailing list unless they sign out.

Spudm is back to 4 days.

We will send out an internet questionnaire about the conference again after this conference

3. The treasurer's reports are presented and approved.

4. The workshops held in 2006 and 2007 (so far) are presented. We are happy that there have been quite a few workshops; many more than before.

5. Proposed modifications in the Articles and Standing Orders of the EADM are presented to the members and put to the vote (enough members are present (&gt; 30) to make the vote legal).
<h1>Articles</h1>
Art. 24

was:            The Executive Board is elected by the members

change:      The members elect the President-Elect and the Member at Large of the              Executive Board

Art. 27

was:            After the Executive Board has been elected, it appoints from its midst the           Secretary-Treasurer and the Newsletter Editor

change:      After the President-Elect and the Member at Large have been elected        they            appoint together with the new President a Secretary-Treasurer and a                          Newsletter Editor

Agreed
<h1>Standing Orders</h1>
Clause 2

.. nominations of a candidate to serve as President-Elect and

was:            of candidates to serve on the Executive Board

change:      of a candidate to serve as Member at Large

Agreed

Clause E:

was:           The Executive Board has at most 2 members with the same nationality.              The President and the President-Elect have a different nationality.

change:      delete

Not agreed

The secretary-treasurer (Cilia Witteman) will have these changes made.

NB (October 2007): Since the costs of formally changing these Articles, through the notary, turns out to be quite high (575 Euros excl. 19 % VAT), the Board decided to keep two files: (1) the up-dated articles and (2) the notarized articles. When EADM has many changes to make, we can then do all the changes at once.

6. The next Spudm organisers are presented, as well as the next Prize committees:

Spudm 2009 will be in Rovereto. Organising committee: Nicolao Bonini, Dinos Hadjichristidis (Trento)(Local organisers); Rob Ranyard (for the Eadm Board), Elke Weber (USA member), person from 2011 Spudm organisation.

For Spudm 2011: there are two possibilities: Barcelona (Robin Hogarth) and Toulouse (Gaëlle Villejoubert). Robin and Gaëlle will investigate, and report before the end of October.

No other cities volunteer during the meeting.

2009 De Finetti prize committee: Pieter Koele (chair), Dan Goldstein, Mandeep Dhami, Wibecke Brun.

2009 Jane Beattie prize committee: Robin Hogarth (chair), Marcel Zeelenberg (this year's winner), Nigel Harvey, Ilana Ritov.

7. Future of EADM

The aim is to facilitate and promote decision research.

Gaëlle gets very positive reactions to her proposal of a dynamic, professional website. She foresees contributing editors for different areas. The members vote to make money availbale for her plans.

John and Robin propose the PR-offensive. Aims are: to lobby at the European level to increase funding for DM research, to help create positions for young DM researchers in Europe, to give or increase service to the public. Ideas are to get publicity around workshops and conferences. John's son will advise us how to het the right angle to interest policy makers and journalists, e.g. by making press releases or flyers in all countries. Other ideas are to mention EADM in grant proposals, to find reviewers through the website, and to publish successful grant proposals on the website.

A requirement added to workshop-funding could be to send out a press release before the workshop.

John and Robin also get the green light to go ahead with their plans.

Some members volunteer to assist Gaëlle and/or John and Robin; more help is welcome.

8. John Maule hands over the chair to Robin Hogarth, the new President.

The new board members (Ilana Ritov as president-elect and Rob Ranyard as member-at large) are welcomed by the new President (Robin Hogarth).

9. Nicolao Bonini presents very attractive slides about the location of the next Spudm, Roverto.  We look forward to it.

Cilia Witteman
