---
title: "Minutes, Rovereto, Italy, August 2009 "
date: 2013-07-09
categories: ["EADM Minutes"]
---

Present: the 2007-2009 board and the 2009-2011 board (Robin Hogarth, Ilana Ritov, Rob Ranyard, Gaelle Villejoubert, Nicolao Bonini, Fergus Bolger, Cilia Witteman), 45 members.

All decisions proposed by the board (see minutes of the August 2009 Executive Board meeting) are accepted by the members.
<ul>
	<li>The financial reports of 2007 and 2008 are approved.</li>
	<li>The maximum sponsorship of workshops is raised from € 2250 to € 3000, for at most 3 workshops a year.</li>
	<li>Because of the high banking costs, full members will from 2010 pay €30, students €15. People will pay membership fees for 2 years while registering for Spudm. So there will be a last 1-year payment in 2010.</li>
	<li>After Toulouse is voted away, the meeting is happy to have the next Spudm 2011 in Kingston upon Thames, United Kingdom.</li>
	<li>An offer is made to investigate the option that Haifa will host Spudm in 2013; after the meeting Barcelona is also proposed.</li>
	<li>The 2011 De Finetti committee will consist of Pieter Koele (chair), Benjamin Scheibehenne (this year’s winner), Mandeep Dhami and Rob Ranyard.</li>
	<li>The 2011 Jane Beattie committee will consist of Ilana Ritov (chair), Marcel Zeelenberg, Ellen Peters and Nicolao Bonini.</li>
</ul>
Members are exhorted to make more active use of the website. A member proposes to put the programs of all previous Spudm meetings on the website. Gaelle will look into this. She ask for assistance with the website, and for any interested member to contact her.

Robin introduces the new board members: Nicolao as president-elect and Fergus as member-at-large.Ilana thanks Rob and Robin for all their work for Eadm in the past 2 years, and presents them with an engraved wooden testimony of their board-membership.
