---
title: "Registration open for SPUDM 24"
date: 2013-08-05
categories: ["News"]
---

The European Association for Decision Making invites you to attend its next biannual 24th Subjective Probability, Utility, and Decision Making Conference (SPUDM 24), which will be held at IESE Business School – University of Navarra in Barcelona, Spain, on August 18-22, 2013.

We are pleased to announce that the registration for the conference is already open and available at:

<a href="http://forms.iese.edu/AppNET/events/SPUDM24/registration.aspx">http://forms.iese.edu/AppNET/events/SPUDM24/registration.aspx</a>

The conference will feature the following invited speakers:

*        Timothy D. Wilson, University of Virginia, USA

*        Colin F. Camerer, California Institute of Technology, USA

*        Robin Hogarth, Universitat Pompeu Fabra, Spain

*        Ralph Hertwig, Max Planck Institute for Human Development, Berlin, Germany

Attending this meeting will also be an opportunity to discover Barcelona, one of the most unique and architecturally distinctive cities of the world. Barcelona is the capital of Spain’s Catalan region, which has produced a number of the world’s most prominent artists including Pablo Picasso and Salvador Dalí. The architect Antoni Gaudí also left his indelible mark on the city through a number of remarkable buildings such as La Sagrada Familia, La Pedrera, and La Casa Batlló.

We look forward to seeing and welcoming you in Barcelona!

The local organizing committee:

Elena Reutskaja (IESE, Spain); Mario Capizzani (IESE, Spain), Franz Heukamp (IESE, Spain), and Robin Hogarth (UPF, Spain).
