---
title: "Review of Perspectives on Thinking, Judging, and Decision Making"
date: 2013-05-22
categories: ["News"]
---

Perspectives on Thinking, Judging, and Decision Making is a collection of cutting edge research that offers an approachable and up to date landscape of the judgment and decision making area.

The book is great: Read it! ... Not convinced yet? Well, here’s more:<i> </i>

<i></i>This Festschrift is a great source of knowledge and inspiration for anyone interested in the way we think, judge, reason and make decisions. We would not expect less of a tribute to Karl-Halvor Teigen, who blazed many trails in the social-cognitive sciences and whose scientific and human contribution stimulates much current research.

At first the book may appear as a collection of (very interesting) papers that presents innovative theoretical or empirical findings at both a basic and an applied level (e.g., chap. 12 looks at the determinant of stock market anomalies). But the book is more than a collection of (very good) chapters. The chapters share a vision of human cognition and an objective.

The chapters approach human cognition as an enigma, wondering for example, “how do we think?” and “how could we think better?” The questions examined stem from surprising details, peculiar phenomena and pitfalls of reality observed in our lives. All these questions arise from daily life and have thus pervasive implications. This bottom-up approach is the backbone of the book. This approach prompts us - researchers, researchers-to-be or simply inquisitive minds - to be inspired by what surrounds us and to root our reflections about people and their mental processes in people’s own (subjective) reality. The bottom-up approach helps to question pre-established views and encourages research creativity and, in doing so, provides a refreshing perspective on the challenges emerging in thinking, judgment and decision making sciences.

Of course, the book does not only raise questions; international experts provide insightful answers. Drawn from various disciplines, the authors tackle human cognition from different angles and provide the reader with varying views, methods and reflections. <i>Perspectives on thinking, judging, and decision making </i>examines different factors that contribute to enhance or hinder human cognition; such as when and where information is provided, to what is it compared, and who is around us. The multiplicity of constructs under focus and the use of various lenses contribute to a meaningful picture of the marvels and snares of human cognition. The book shows that our judgments and decisions are often based on irrelevant cues, are occasionally normative, but above all, are always fascinating.

The book testifies to the excellent research that is conducted in judgment and decision making and to the concerns of this field for progress in knowledge and lives. Some chapters offer valuable theoretical developments (e.g., chap. 1 develops a Taxonomy of uncertainty) whereas others provide new insights on past findings and enable us to rediscover previous work in a new light (e.g., chap. 21 walks us back to the work of Descartes on (un)conscious and emotion). The book also includes chapters that help us to re-think the role of accepted findings (e.g., chap. 9 revisits the role of intuition in conjunction fallacy) and to integrate new findings from one field into a known framework from another (e.g., chap. 22 integrates findings on ethnics bias in the dual system framework).

Beyond being a source of academic knowledge, this book is also highly entertaining. Personally, what contributed most to my reading experience, and what makes the book essentially different from other books on JDM, is the inclusion of many comic anecdotes and fond moments that the authors shared with Karl-Halvor. The book testifies to the fun and friendship fostered during scientists' careers. I take the occasion of this review to thank the editors for their efforts, time and commitment putting this book together, it was really worth it!

<i>Perspectives on Thinking, Judging, and Decision making</i> makes a great contribution to advancing our understanding of how we think, judge and decide and of the factors that can help us do better. The book is an excellent resource for researchers and an appealing introduction to the field for beginners.

<a href="http://eadm.eu/index.php?option=com_comprofiler&amp;task=userprofile&amp;user=870&amp;Itemid=327" target="_blank">Marie Juanchich</a>
<a href="mailto:M.Juanchich@kingston.ac.uk">M.Juanchich@kingston.ac.uk</a>
