---
title: "SPUDM 2013 Call for papers and submissions"
date: 2013-05-23
categories: ["News"]
---

The European Association for Decision Making invites submissions for its 2013 Biennial SPUDM24 conference to be held at IESE Business School, Barcelona, Spain from Sunday, the 18th till Thursday, the 22nd of August 2013.

Submissions of paper abstracts, poster abstracts, and proposals for workshops are invited on any topic in basic and applied judgment and decision making research.

Deadline for all submissions is March 8, 2013.

The organizing committee is pleased to announce that the conference will feature the following invited speakers:
<ul>
	<li>Timothy D. Wilson, University of Virginia, USA</li>
	<li>Colin F. Camerer, California Institute of Technology, USA</li>
	<li>Robin Hogarth, Universitat Pompeu Fabra, Spain</li>
	<li>Ralph Hertwig, Max Planck Institute for Human Development, Berlin, Germany</li>
</ul>
Attending this meeting will also be an opportunity to discover Barcelona, one of the most unique and architecturally distinctive cities of the world. Barcelona is the capital of Spain's Catalan region, which has produced a number of the world's most prominent artists including Pablo Picasso and Salvador Dalí. The architect Antoni Gaudí also left his indelible mark on the city through a number of remarkable buildings such as La Sagrada Familia, La Pedrera, and La Casa Batlló.

For call for papers and submissions, please, visit

<a href="http://www.iese.edu/en/events/OtrosEventos/SPUDM24/Home/Home.asp">http://www.iese.edu/en/events/OtrosEventos/SPUDM24/Home/Home.asp</a>

We look forward to seeing you and to welcoming you to Barcelona!

The local organizing committee:

Elena Reutskaja, Mario Capizzani, Franz Heukamp, and Robin Hogarth
