---
title: "Tenure Track Position: Judgment and Decision Making and the Law"
date: 2013-05-23
categories: ["Jobs"]
---

The Behavioral Science area at the Technion - Israel Institute of Technology, (Faculty of Industrial Engineering and Management) invites applications for aTenure track position in Judgment and Decision Making and the Law starting as soon as possible. The position is open to all academic ranks starting from assistant professor. The position will be partially funded by a grant from the Israel Science foundation, as part of its Israel Centers Of Research Excellence (ICORE) program.

The position is in the Center for Empirical Studies of Decision Making and the Law, a joint center for Hebrew University and the Technion.As part of the generous funding of the ICORE program, the chosen candidate will receive a research grant of about NIS 160,000 a year which will be renewed annually until 2018. This amount is in addition to the institutional salary and startup grant. The ICORE supports only returning Israeli citizens.Applications from scientists with a research focus in several of the following areas are especially encouraged: Decision making, Legal studies, Neuroeconomics, Behavioral Finance.

Applicants should submit

1) A cover letter describing their research interests.

2) A curriculum vitae.

3) Names and contact details of three recommenders.Review of applications will be on a first come - first reviewed basis and will continue until the position is filled.

Applications should be sent to:Prof. Eldad Yechiam at <a href="mailto:yeldad@tx.technion.ac.il">yeldad@tx.technion.ac.il</a>. For any further information please contact Prof. Eldad Yechiam at <a href="mailto:yeldad@tx.technion.ac.ilProf">yeldad@tx.technion.ac.il </a>

Faculty of Industrial Engineering and ManagementTechnion - Israel Institute of TechnologyTechnion City, Haifa 32000, Israel

Phone: (972) 4-829-4420

Fax: (972) 4-829-5688

Website: <a href="http://techunix.technion.ac.il/~yeldad/">http://techunix.technion.ac.il/~yeldad/</a>
