---
title: "Workshop: Navigating Clinical Uncertainty"
date: 2015-02-02
categories: ["News"]
---

<p class="p1"><span class="s1"><b>Navigating Clinical Uncertainty</b></span></p>
<p class="p1"><b>10th European Workshop on Clinical Reasoning and Decision Making </b><b>&amp;</b></p>
<p class="p1"><span class="s1"><b>COGITA: Gut Feelings in General Practice</b></span></p>
March 26<sup>th</sup> – March 28<sup>th</sup> , 2015

Marburg (Germany)

Dear colleagues,

we gladly announce the 10th workshop on Clinical Decision Making and Diagnostic Reasoning, this time in collaboration with the COGITA-group, a European network of researchers focusing on the role of gut feelings in the diagnostic reasoning of general practitioners. This conference will be hosted by the Departments of General Practice and Clinical Psychology at the University of Marburg (Germany). The aim of this interdisciplinary workshop is to bring together researchers from decision and clinical science as well as clinicians to share their ideas, their research and their experience. The workshop is sponsored by the European Association for Decision Making and attendance is free.

For more information see

<a href="http://www.uni-marburg.de/fb20/allgprmed/europeanworkshop">http://www.uni-marburg.de/fb20/allgprmed/europeanworkshop</a>

We are looking forward to seeing you all in Marburg!

&nbsp;

The Scientific Committee:

Norbert Donner-Banzhoff (Marburg/D), Laurence Claes (Leuven/B), York Hagmayer (Göttingen/D), Erik Stolper (Maastricht/NL), Winfried Rief (Marburg/D), Cilia Witteman (Nijmegen/NL)
