"""Generates the Quarto site's migrated content: reads the extracted
WordPress JSON, classifies each item via content_map, rewrites its
internal links and media references, and writes one .qmd file per kept
item. Also writes CONTENT_AUDIT.md listing everything that was dropped.

This is a one-time migration script, run once against the exported
WordPress database -- not part of the served site.
"""

import json
from pathlib import Path

from content_map import resolve_target
from rewrite import (
    rewrite_attachment_links,
    rewrite_internal_links,
    rewrite_wp_uploads_links,
)

REPO_ROOT = Path(__file__).parent.parent
EXTRACTED = Path(__file__).parent / "_extracted"
UPLOADS_ROOT = Path(
    "/Users/michael/git_stuff/wp_eadm/eadm-eu-20260914-054440-ujh0nuxckrsu/uploads"
)
IMAGES_OUT = REPO_ROOT / "images"
FILES_OUT = REPO_ROOT / "files"


def load(name):
    return json.loads((EXTRACTED / name).read_text())


def build_categories_by_post_id(categories):
    result = {}
    for row in categories:
        result.setdefault(row["post_id"], set()).add(row["category"])
    return result


def build_attachment_files(attachments):
    return {a["id"]: a["file"] for a in attachments if a["file"]}


def build_slug_to_path(items, categories_by_post_id):
    slug_to_path = {}
    for item in items:
        target = resolve_target(item, categories_by_post_id)
        if target is None:
            continue
        section, filename = target
        path = f"{section}/{filename}" if section else filename
        slug_to_path[item["slug"]] = path
    return slug_to_path


def yaml_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_frontmatter(item, categories_by_post_id):
    lines = ["---", f'title: "{yaml_quote(item["title"])}"']
    if item["type"] == "post":
        lines.append(f"date: {item['date'][:10]}")
        cats = sorted(categories_by_post_id.get(item["id"], set()))
        if cats:
            quoted = ", ".join(f'"{yaml_quote(c)}"' for c in cats)
            lines.append(f"categories: [{quoted}]")
    lines.append("---")
    return "\n".join(lines)


def main():
    pages = load("pages.json")
    posts = load("posts.json")
    items = pages + posts
    categories_by_post_id = build_categories_by_post_id(load("categories.json"))
    attachment_files = build_attachment_files(load("attachments.json"))
    slug_to_path = build_slug_to_path(items, categories_by_post_id)

    written, dropped = [], []
    for item in items:
        target = resolve_target(item, categories_by_post_id)
        if target is None:
            dropped.append(item)
            continue
        section, filename = target
        out_dir = REPO_ROOT / section if section else REPO_ROOT
        out_dir.mkdir(parents=True, exist_ok=True)

        content = item["content"]
        content = rewrite_attachment_links(
            content, attachment_files, UPLOADS_ROOT, IMAGES_OUT, FILES_OUT
        )
        content = rewrite_wp_uploads_links(content, UPLOADS_ROOT, IMAGES_OUT, FILES_OUT)
        content = rewrite_internal_links(content, slug_to_path)

        frontmatter = build_frontmatter(item, categories_by_post_id)
        (out_dir / f"{filename}.qmd").write_text(f"{frontmatter}\n\n{content}\n")
        written.append((item, section, filename))

    write_content_audit(dropped, written)
    print(f"Wrote {len(written)} .qmd files, dropped {len(dropped)} items.")


def write_content_audit(dropped, written):
    from content_map import DROP_IDS

    lines = [
        "# Content Audit",
        "",
        "Generated by `tools/transform.py` — do not hand-edit. Lists every",
        "published WordPress page/post that was dropped or merged during",
        "migration, and why.",
        "",
        "## Dropped or merged items",
        "",
    ]
    for item in sorted(dropped, key=lambda i: i["id"]):
        reason = DROP_IDS.get(item["id"], "unspecified")
        lines.append(f"- **{item['title']}** (WP id {item['id']}, slug `{item['slug']}`): {reason}")
    lines += ["", f"## Migrated: {len(written)} items", ""]
    (REPO_ROOT / "CONTENT_AUDIT.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
